/*
Copyright 2017 Redis-Operator

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	redis_v1 "github.com/amadeusitgroup/redis-operator/pkg/api/redis/v1"
	versioned "github.com/amadeusitgroup/redis-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/amadeusitgroup/redis-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/amadeusitgroup/redis-operator/pkg/client/listers/redis/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// RedisClusterInformer provides access to a shared informer and lister for
// RedisClusters.
type RedisClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.RedisClusterLister
}

type redisClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRedisClusterInformer constructs a new informer for RedisCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRedisClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRedisClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRedisClusterInformer constructs a new informer for RedisCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRedisClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RedisV1().RedisClusters(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RedisV1().RedisClusters(namespace).Watch(options)
			},
		},
		&redis_v1.RedisCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *redisClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRedisClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *redisClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&redis_v1.RedisCluster{}, f.defaultInformer)
}

func (f *redisClusterInformer) Lister() v1.RedisClusterLister {
	return v1.NewRedisClusterLister(f.Informer().GetIndexer())
}
