apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: redis-node
  rules:
  - apiGroups: [""]
    resources:
    - namespaces
    - services
    - endpoints
    - pods
    verbs: ["list", "get"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: redis-node-default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: redis-node
  subjects:
  - kind: ServiceAccount
    name: redis-node
    namespace: default
  # The SA for the redis operator
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "redis-node"
